### ISSUE TITLE
simply doesn't work

### ISSUE THREAD

**Issue by CyberDudeJ** [kaiyga/pterodactyl-nginx#1]
`[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
Jexactyl: Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
Pulling from kaiyga/vectordocs 
Status: Image is up to date for ghcr.io/kaiyga/vectordocs:nginx-stream 
Digest: sha256:d2463c7a779ffc20524b08783cae9009f5e50077fc2578ac834c0d6b34f3b157 
[Pterodactyl Daemon]: Finished pulling Docker container image
exec /bin/ash: exec format error
Jexactyl: Server marked as running...
Jexactyl: Server marked as offline...
[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 1
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...`

**Comment by CyberDudeJ** [comment]
just like the other eggs this one just does not work.

**Comment by kaiyga** [comment]
Sorry that i answer so late.

Okay. You send me commit about ./start.sh
- #2 

I did experiment and swaped ash to bash. And install process don't started. Because this  a docker images not have bash shell. Only ash.
I think you, changed all to bash. And install processed don`t started:D
Return all your changes to normal. Or delete EGG and install again 
![image](https://github.com/kaiyga/pterodactyl-nginx/assets/92279086/c14725fc-02ec-46d6-b748-f77946d40ab9)
